### ISSUE TITLE
Extension doesn't load properly on Windows in WSL2 environment.

### ISSUE THREAD

**Issue by baldimir** [redhat-developer/vscode-redhat-account#18]
Hello, I am trying to migrate from IntelliJ IDEA to VS Code, so I wanted to install OpenShift Connector extension. It has a dependency on this extension. When I click on the OpenShift pane, I get an error:

"Cannot activate the 'OpenShift Connector' extension because it depends on the 'Red Hat Authentication' extension, which is not loaded. Would you like to reload the window to load the extension?"

When I click reload, it reloads the editor but the Red Hat Authentication still doesn't load properly, so I end in the same situation with the same error. I can attach some logs, but as I am new to the VS Code I am not sure which one. So if you need some logs, please let me know.  

My environment: VS Code on Windows 11 with WSL2 (project open from WSL2 environment, so the editor uses Remote - WSL extension).

**Comment by fbricon** [comment]
does it work without WSL2?

**Comment by baldimir** [comment]
Yes.

**Comment by fbricon** [comment]
Ok this is super weird. I have a Windows box, I used to test it with [vscode-rhoas](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-rhoas), which also depends on vscode-redhat-account for Red Hat authentication, I'm just more familiar with it than the OpenShift one. Everything worked, I managed to log in, create and connect to a Kafka cluster. 
I then installed and opened the OpenShift extension, managed to also log into Red Hat. 

And then I restarted VS Code. This time I saw the same error as you opening OpenShift. But also opening the Kafka explorer. I restarted VS Code once more, started opening the Kafka explorer 1st, same error. OpenShift, same error.

So at this point I have no idea what's wrong, but the good thing is I can reproduce it ;-)

**Comment by fbricon** [comment]
So, when installing, the 1st time vscode-redhat-account is activated, it happens in WSL. Once you reload VS Code, the extension runs locally, if you hover over it in the extension view, it says : "This extension is enabled in Local Extension Host because it prefers to run there", and it links to https://code.visualstudio.com/api/advanced-topics/remote-extensions

According to https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location, you can fix this by setting "remote.extensionKind" properly in your settings.json:

```
{
  "remote.extensionKind": {
    "redhat.vscode-redhat-account": ["workspace"]
  }
}
```
It fixed the problem for me.

**Comment by baldimir** [comment]
Thank you very much, this helped.

**Comment by supernovae** [comment]
Thanks @fbricon  - this addressed the issue for me as well.
